spring:
  datasource:
    username: records_app
    password: records_app
    url: jdbc:postgresql://localhost:5432/records_app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
